steps:
  # build the java application
  - name: gradle:5.6.2-jdk17
    entrypoint: gradle
    args: [ 'assemble' ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stego-be/stego-be-java-application', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stego-be/stego-be-java-application']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'stego-rest-api', '--image', 'gcr.io/stego-be/stego-be-java-application', '--region', 'asia-northeast1']
images:
  - gcr.io/stego-be/stego-be-java-application