spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 500
      connection-init-sql: "SELECT 1"
      validation-timeout: 400
      maximum-pool-size: 10
      max-lifetime: 570000
    #flyway:
    # プロダクションコード実行時はマイグレーションしない
    #enabled: false
  mvc:
    pathmatch:
      # swaggerバグ対策
      matching-strategy: ANT_PATH_MATCHER

server:
  port: ${PORT:8080}

mybatis:
  mapper-locations: classpath:mybatis/*.xml