spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    # プロダクション実行時にはマイグレーションしない
    enabled: false

mybatis:
  mapper-locations: classpath:mybatis/*.xml