spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #flyway:
    # プロダクションコード実行時はマイグレーションしない
    #enabled: false
  mvc:
    pathmatch:
      # swaggerバグ対策
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mybatis/*.xml